#!/usr/bin/env bash
# Phase 6 — render /opt/folio/.env from Secret Manager. Runs ON THE VM as root
# via the folio-render-env.service oneshot unit. Y2 dropped the daily timer —
# this script is invoked manually during rotation.
#
# Behaviour:
#   - Fetch each SM key via VM-attached vm-runtime-sa.
#   - Compose a tempfile (mode 600) with constants + fetched secrets.
#   - Atomically rename to /opt/folio/.env (mode 640, root:docker).
#   - Log SHA256 of the rendered file via journald (no values).
#   - On any fetch failure: keep existing .env, exit 1, log loud.
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-flowitup-folio-prod}"
ENV_FILE="${ENV_FILE:-/opt/folio/.env}"

# SM-key → ENV_VAR mapping (ordered for predictable diffs).
# Skipped: folio-cf-api-token, folio-cf-zone-id (consumed by GitHub Actions, not the VM).
MAPPINGS=(
  "folio-postgres-user=POSTGRES_USER"
  "folio-postgres-password=POSTGRES_PASSWORD"
  "folio-postgres-db=POSTGRES_DB"
  "folio-secret-key=SECRET_KEY"
  "folio-jwt-secret-key=JWT_SECRET_KEY"
  "folio-s3-access-key=S3_ACCESS_KEY"
  "folio-s3-secret-key=S3_SECRET_KEY"
  "folio-s3-bucket=S3_BUCKET"
  "folio-s3-public-endpoint-url=S3_PUBLIC_ENDPOINT_URL"
  "folio-cors-origins=CORS_ORIGINS"
  "folio-next-public-api-base-url=NEXT_PUBLIC_API_BASE_URL"
  "folio-resend-api-key=RESEND_API_KEY"
  "folio-resend-from-email=RESEND_FROM_EMAIL"
  "folio-ratelimit-storage-uri=RATELIMIT_STORAGE_URI"
  "folio-behind-proxy=BEHIND_PROXY"
  "folio-gcs-hmac-access-key=GCS_HMAC_ACCESS_KEY"
  "folio-gcs-hmac-secret-key=GCS_HMAC_SECRET_KEY"
  "folio-admin-bootstrap-password=ADMIN_BOOTSTRAP_PASSWORD"
)

# Constants: not in SM (no rotation, not credentials, internal-only).
# These stay in code for reproducibility.
CONSTANTS=(
  "S3_ENDPOINT_URL=http://minio:9000"
  "S3_REGION=us-east-1"
  "EMAIL_PROVIDER=resend"
  "API_INTERNAL_BASE_URL=http://api:5000/api/v1"
  "FLASK_DEBUG=false"
  "NODE_ENV=production"
)

log() { /usr/bin/logger -t render-env -s "$*" 2>&1; }

[[ $EUID -eq 0 ]] || { log "ERROR: must run as root"; exit 1; }

TMP=$(/usr/bin/mktemp)
chmod 600 "$TMP"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by render-env.sh on $(date -u +%FT%TZ) — DO NOT COMMIT"
  echo "# Source: gcloud secrets in project $PROJECT_ID"
  echo ""
  echo "# Constants (in-code, not Secret-Manager-sourced):"
  for c in "${CONSTANTS[@]}"; do echo "$c"; done
  echo ""
  echo "# From Secret Manager:"
} > "$TMP"

for m in "${MAPPINGS[@]}"; do
  key="${m%%=*}"
  var="${m#*=}"
  if ! val=$(gcloud secrets versions access latest --secret="$key" --project="$PROJECT_ID" 2>&1); then
    # Truncate to first line — gcloud occasionally returns multi-line errors
    # whose body could include cached token fragments. journald is readable by
    # any operator; keep the leak surface tiny.
    log "ERROR: failed to fetch $key — keeping existing .env if any"
    log "  gcloud said: ${val%%$'\n'*}"
    exit 1
  fi
  printf '%s=%s\n' "$var" "$val" >> "$TMP"
done

# Atomic install (overwrites symlinks/inode atomically; fails if perms wrong).
/usr/bin/install -m 640 -o root -g docker "$TMP" "$ENV_FILE"

sha=$(/usr/bin/sha256sum "$ENV_FILE" | /usr/bin/cut -d' ' -f1)
key_count=$(/usr/bin/grep -cE '^[A-Z_]+=' "$ENV_FILE")
log "rendered $ENV_FILE keys=$key_count sha256=${sha:0:16}…"
